version: "3.2"

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    command: npm start
    restart: always

volumes:
  node-modules: